spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/demo_schema
    username: demo_user
    password: 20230601

mybatis:
  mapper-locations: "classpath:mybatis/mappers/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    type-handlers-package: dev.ooae.mybatis.typehandlers
    # 다른 설정들...
    mapper-registry:
      type: org.apache.ibatis.binding.MapperRegistry
      properties:
        lazy-loading-enabled: true
        cache-enabled: true
        default-executor-type: REUSE
        # 기타 MapperRegistry 설정
